Fixing CI issues
Few fixes i've put in to fix some build issues:
* Added a default for `CHIP_DEVICE_CONFIG_MAX_DISCOVERED_IP_ADDRESSES`
** The variable is not defined since a bunch of examples don't pull in the `src/include/platform/CHIPDeviceConfig.h` file which defines this variable and this causes the build to fail.
** This seemed like the best place to put this since this is a library and doesn't have dependencies on the other config files.

* Fixed the cachedVideoPlayers variable to be set correctly, otherwise
  there is a build complaint:
```
error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘class TargetVideoPlayerInfo’; use assignment or value-initialization instead [-Werror=class-memaccess]
```

* Did a check of the folder existence in the strip package otherwise it
  fails if it can't find the folder, probably because of something messy
with our instance of the CI setting some path (doesnt' happen in master)

* Removed extra log in commissioning server, it doesn't exist in
  master

* Added some targets into the testdata targets file

* Fixed some uses of %zu and 0x%u since the CI checks for it